### ISSUE TITLE
Размытое изображение на мобильной платформе

### ISSUE THREAD

**Issue by ghost** [fotov/qr#1]
Доброго времени суток.
Подскажите, как исправить проблему размытости кода.
![Screenshot_1](https://user-images.githubusercontent.com/42896502/158150426-429807e0-feed-4221-8bf0-dd34004d7314.png)
![Screenshot_2](https://user-images.githubusercontent.com/42896502/158149878-7147851b-98cd-4f56-9e6f-f8855fcd0899.png)

**Comment by fotov** [comment]
Ну, в целом размытие делает сама платформа.
Варианты для исправления:
1. Переработать алгоритм, чтобы дублировать пиксели x2, x3 или x4 (я делал, но это уменьшает производительность)
2. Сделать поле HTML документа в который интегрировать картинку, но там тоже есть засады (https://stackoverflow.com/questions/8597081/how-to-stretch-images-with-no-antialiasing)

**Comment by ghost** [comment]
Спасибо за ответ
